### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by fulldecent** [jcubic/jquery.rotate#3]
could you please link to a hosted version

**Comment by jcubic** [comment]
Is jquery.rotate on CDN?

**Comment by fulldecent** [comment]
It is not, but I believe https://www.jsdelivr.com/?query=rotate would want to add this module.

**Comment by jcubic** [comment]
If you need this you can add jQuery.rotate to jsdelivr, read the [CONTRIBUTING.md](https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md) file for deteails how to do it. I don't think it's big enough to include it in CDN.

**Comment by ilyalyo** [comment]
Added: https://github.com/jsdelivr/jsdelivr/pull/13688

**Comment by jcubic** [comment]
great.
